// GENERAL ACTIONS
export const CHANGE_THEME = 'CHANGE_THEME';

// HOMEPAGE ACTIONS
export const TEST_HOMEPAGE = 'TEST_HOMEPAGE';
export const ALL_CATEGORIES = 'ALL_CATEGORIES';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

// STOREPAGE ACTIONS
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';