// GENERAL ACTIONS
export const CHANGE_THEME = 'CHANGE_THEME';

// HOMEPAGE ACTIONS
export const TEST_HOMEPAGE = 'TEST_HOMEPAGE';

// STOREPAGE ACTIONS
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';